name: Build kernel packages

on:
  push:
    branches: [ "main", "master", "work" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: ./scripts/ci-build.sh

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: cubie-kernel-artifact
          path: out
          if-no-files-found: error
